### ISSUE TITLE
Allowing use SQL native driver if ODBC drivers missing

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inbodb#22]
While preparing the coding club of next Tuesday, it seems that the installation of `inbodb` package fails for some people. They apparently do not have any ODBC driver installed. Instead, they use standard SQL Native driver.
This is the error they get: `The 'ODBC Driver for SQL Server' is missing. Please install it or contact your system administrator.`
which is arisen by https://github.com/inbo/inbodb/blob/master/R/connect_inbo_dbase.R#L50-L58

Thanks @Jo-Loos for spotting this. 

Jo and I suggest the following improvements:
1. search for SQL Native driver if search for ODBC fails
2. arise a warning instead of an error maybe suggesting to install ODBC drivers in the future or contacting IT helpdsek of your organization

Using SQL native drivers instead of ODBC ones will not change really very much for "typical" users.

Moreover, solving this issue is quite important for allowing some INBO colleagues to follow the coding club of Tuesday. One has been already helped by ICT helpdesk, another one will be helped very fast in next hours, but I cannot guarantee everybody will carry out the tests I suggested in the email reasonably on time.

What do you think about it? Many thanks.

**Comment by florisvdh** [comment]
See also #17, I think this is a continuation (or duplication) of that issue.

**Comment by damianooldoni** [comment]
Thanks @florisvdh. I will  switch to #17.
