### ISSUE TITLE
add information on inboveg

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/inbodb#25]
As discussed: it would be useful if a link to information on the data of inboveg would be added to the introduction of the vignet on retrieving data from the inboveg database.

**Comment by ElsDeBie** [comment]
this is already done, no? at least in the last branch I created from the master (work needed-branch). " ... More information? Check out https://www.vlaanderen.be/inbo/en-gb/data-applications/inboveg/ "

**Comment by ElsLommelen** [comment]
I'm not sure, I don't see the link neither on the [website](https://inbo.github.io/inbodb/articles/get_data_inboveg.html), nor in the code itself.  Could you please check, because I don't know where you put it exactly?
