### ISSUE TITLE
add info to function "get_florabank_traits() "

### ISSUE THREAD

**Issue by leymanan** [inbo/inbodb#26]
Is het mogelijk om ook de bron toe te voegen aan de traits? (zit wellicht in tblTaxonKenmerk?)
Of een extra argument aan de functie toevoegen zodat men de keuze heeft om de bron al dan niet mee in te laden.
Bv. bij indicator oud-bos: handig om te weten dat de bron Hermy is en niet Cornelis .

**Comment by ElsLommelen** [comment]
Is dit issue eigenlijk afgewerkt?  We hebben voor het gemak de PR gesloten, maar @leymanan heeft nog geen reactie gegeven op het resultaat.  @leymanan check jij bij gelegenheid even of bovenstaand issue intussen in orde is, en sluit je dit issue als dit het geval is?  (Heeft geen haast.)

**Comment by leymanan** [comment]
Is in orde zo, bedankt!
