### ISSUE TITLE
Test if connection works

### ISSUE THREAD

**Issue by ThierryO** [inbo/inbodb#34]
https://github.com/inbo/inbodb/blob/34a02f59fab06028e4ec9e4771cbe990ae449cda/R/connect_inbo_dbase.R#L61
If the connection is not open, issue an error with some sensible suggestions.
- are you connected to the INBO network?
- is the VPN connection active when not @ INBO?
- did you open a tunnel through the bastion?

**Comment by ElsLommelen** [comment]
Good idea!  Maybe I could just catch the errors and rewrite the messages for some common cases?  Not having the rights to read the database is another common problem...  (And they both give different cryptic messages.)
