### ISSUE TITLE
re-licencing inbodb

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/inbodb#36]
inbodb is currently MIT licensed, but I noticed that the package odbc, from which we 'rewrite' function dbDisconnect, has a [`GNU Affero General Public License`](https://www.gnu.org/licenses/why-affero-gpl.en.html) (a variant of GPL-3 that additionally prevents from using derived software on servers without publicly sharing).  This license requires to publish derived products under the same license.

I aim to change this license, but in order to do so, I need a formal acceptance from all contributors.  Could you please all let me know if you agree by a reply in this issue?

- [x] Els Lommelen (@ElsLommelen)
- [x] Hans Van Calster (@hansvancalster)
- [x] Els De Bie (@ElsDeBie) 
- [x] Floris Vanderhaeghe (@florisvdh)
- [ ] Stijn Van Hoey (@stijnvanhoey)

**Comment by ElsLommelen** [comment]
Eh, I'm not sure it can be tracked who has added the ticks.  To avoid the possibility of cheating, please add a reply here, or at least add a thumb, like @ElsDeBie did.

**Comment by florisvdh** [comment]
> it can be tracked who has added the ticks

Yes, you can see it in the dropdown at the top:

![afbeelding](https://user-images.githubusercontent.com/19164640/124560512-2c262200-de3d-11eb-97ad-cdf934de9182.png)

**Comment by ElsLommelen** [comment]
Ah, ok, I didn't know that, thanks!  Then you can just ignore my previous comment.  ;-)

**Comment by ElsLommelen** [comment]
After having a second look at the licence of odbc, I'm a bit confused: the DESCRIPTION file still mentions MIT, but in the LICENSE file [the part with the MIT regulations was removed in 2017](https://github.com/r-dbi/odbc/commit/10dec09e253dea78737e37c769a2450c2300aa3e), and only the texts `YEAR: 2016` and `COPYRIGHT HOLDER: RStudio` were kept.  RStudio has `AGPL` as a license, that's why I concluded yesterday that odbc would be covered by the same license, but now I realise the same copyright holder implies not necessarily the same license.  I checked for the other packages under r-dbi, and they have `LGPL` or `GPL` as a license.

I suppose we 'll be fine if we use one of the licenses of the `GPL` family?  In this case I would propose `GPL-3`, then we can easily setup the automated tests of the [checklist](https://inbo.github.io/checklist/index.html) package.

**Comment by florisvdh** [comment]
It appears that the MIT license refers to the nanodbc source code (included in the repo), as seen in inst/COPYING. I'm not sure how the plain 'copyright' license here should be dealt with. Since there seems to be a contradiction between DESCRIPTION and LICENSE, you could also file an issue at odbc, refer to the difference with other r-dbi repositories and see how they handle this.

**Comment by ElsLommelen** [comment]
@florisvdh, thanks for your suggestion, I did it (without refering to this whole conversation ;-) ).
