### ISSUE TITLE
Link to GitHub repo via icon is broken

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inbodb#41]
I was on https://inbo.github.io/inbodb/ and I clicked on the GitHub icon (see screenshot below). Unfortunately I am redirected to this not existing page: https://github.com/inbo/%7B%7B%7B%20Package%20%7D%7D%7D

![image](https://user-images.githubusercontent.com/33662631/150105298-761bd3d5-2ae9-4175-956c-4c05cd131546.png)

**Comment by ElsLommelen** [comment]
Good catch!  I'll fix this in the next version.
